name: Update FPGA Database

on:
  push:
    paths:
      - 'database/**'
      - 'scripts/**'
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight UTC
  workflow_dispatch: # Allows manual triggering

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sqlite3
        
    - name: Update database
      run: |
        cd database
        python init_db.py
        cd ../scripts
        python export_data.py
        
    - name: Commit changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add docs/data/boards.json
        git commit -m "Automated data update [skip ci]" || echo "No changes to commit"
        git push