name: Update FPGA Database

on:
  push:
    paths:
      - 'database/**'
      - 'scripts/**'
  schedule:
    - cron: '0 0 * * *' # Daily at midnight UTC
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # This is crucial for pushing changes
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Needed for proper git history
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Update database
      run: |
        cd database
        python init_db.py
        cd ../scripts
        python export_data.py
    
    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        git add docs/data/
        git diff --cached --quiet || git commit -m "Automated data update [skip ci]"
        git push